services:
  postgres:
    image: postgres:18
    container_name: production-intelligence-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: production_intelligence
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ohm12345@

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: